/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define ADC_BASE_REG              0x40012000UL
#define ADC_CR1_REG_OFFSET        0x04UL
#define ADC_CR1_REG_ADDRESS       (ADC_BASE_REG + ADC_CR1_REG_OFFSET)

#define RCC_BASE_REG              0x40023800UL
#define RCC_APB2_REG_OFEST        0x44UL
#define RCC_APB2_ENABLE_REG       (RCC_BASE_REG + RCC_APB2_REG_OFEST)

int main(void)
{
// First Enable the clock for ADC1 which is on BUS APB2 on bit 8
  uint32_t *pRccApb2reg = (uint32_t*) RCC_APB2_ENABLE_REG;
  (*pRccApb2reg) |=(1<<8);

// Write 1 on SCAN bit of ADC1 CR1 Register
  uint32_t *pAdcCr1Reg = (uint32_t*) ADC_CR1_REG_ADDRESS;
  (*pAdcCr1Reg) |=(1<<8);

	for(;;);
}
