/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RAM_MEMORY_ADDRESS 0x20000004U

int main(void)
{
	uint32_t  value = 0;
	uint32_t volatile *ptr = (uint32_t *)RAM_MEMORY_ADDRESS;

	while(1)
	{
		value=*ptr;
		if(value !=0 )
			break;
	}

	for(;;);
}
