/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f401xx.h"
#include "stm32f401xx_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay()
{
  for(int i =0 ; i<500000; i++){}
}

int main(void)
{
  GPIO_Handle_t GPIOLedHandle;

  GPIOLedHandle.pGPIOx=GPIOA;

  GPIOLedHandle.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
  GPIOLedHandle.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUTPUT;
  GPIOLedHandle.GPIO_PinConfig.GPIO_PinSpeed=GPIO_OP_SPEED_VERY_HIGH;
  GPIOLedHandle.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PUSH_PULL;
  GPIOLedHandle.GPIO_PinConfig.GPIO_PinPuPdControl=GPIO_PIN_PULL_UP;
  
  GPIO_PeriClockControl(GPIOA,ENABLE);

  GPIO_Init(&GPIOLedHandle);
  
  while (1)
  {
    GPIO_ToggleOutputPin(GPIOA,GPIO_PIN_NO_5);
    delay();
  }
  

	for(;;);
}
